### ISSUE TITLE
Agent dvr code 

### ISSUE THREAD

**Issue by bkbilly** [ispysoftware/iSpy#109]
I was wondering about the source code of the agent dvr.
Is it open source?
If so, is there a repository?
Thanks!

**Comment by ispysoftware** [comment]
Hello no it's not open source at the moment. Might make it open source if there is a big enough demand for it.

**Comment by bkbilly** [comment]
I installed Agent DVR on my Linux PC and I want to have access from another because they are in the same network, but they don't have internet.
When I try to connect from the other PC, it asks me for remote access to the ispyconnect 
Is it possible to do it without that?

**Comment by ispysoftware** [comment]
You'd need to install an SSL certificate on the pc running agent

**Comment by kdub454** [comment]
Hey there, also looking for an NVR solution for my home that I can contribute to.
After playing around with the Agent I had a few minor enhancements I wanted to add and was disappointed to see it's not open-source yet.

**Comment by ispysoftware** [comment]
hello yes you just use the LAN IP address and port to sonnet to it - should
work unless a firewall is blocking the connection.

**Comment by adamkrawczyk** [comment]
Hi, 

When can we expect to see agent dvr open sourced?

Best

**Comment by joe733** [comment]
Same here, please :)

**Comment by ispysoftware** [comment]
There are a few commercial licensing issues with open sourcing agent unfortunately. We have open sourced our plugins though...

https://github.com/ispysoftware/AgentDVR-Plugins

**Comment by EternityForest** [comment]
Yeah, I'd also love to see it as FOSS, it's the only good DVR I've found so far, and it's always better not to rely on closed stuff, but I understand there's always legal and business concerns.

**Comment by betaproger2** [comment]
please give the code agent dvr

**Comment by tensiondriven** [comment]
Thanks for open-sourcing the plugins, making Agent NVR free, and providing a docker image for Agent NVR.  I agree that Agent is the most fully-featured linux-compatible NVR available, and I love that it's free.  While having it open-sourced would be great, and some users will probably not adopt it specifically because they can't be sure of what its doing, I think it's wonderful that there exists a free fully-featured NVR for linux.  Nice work.

It's also worth noting that Agent NVR's *entire featureset* is free for personal use; there is no paywall for advanced features, or an effort to hook people on Agent and then artificially limit its capabilities for profit.   I think this may be overlooked by people who think of iSpy/Agent as commercial software and immediately dismiss it out-of-hand.

I think that iSpy is doing a great service to the community by providing Agent with no paywall/upsell, and I hope that others see it similarly.

**Comment by LarsHilden** [comment]
I have a feature request for Agent DVR. I like to have a buffered pre-recording as a default setting to make sure that I record events that occur even before motion is detected.
When stepping through recordings, I need to wait for the playback of the buffered time, which usually doesn't contain anything interesting. It would be nice to have a couple of options for starting playback at a fixed time in a recording or a dynamic function that starts playback at the point in the video where motion is first detected. This will save some time when stepping through a large number of recordings and still preserve the pre-recordings that matter.

**Comment by ispysoftware** [comment]
@LarsHilden  sure will be in next update, option under Server Settings - Playback, "Skip to Content" - will skip to the first motion event above the min trigger point.

**Comment by exaiyo** [comment]
> There are a few commercial licensing issues with open sourcing agent unfortunately. We have open sourced our plugins though...

My only apprehension to trying out agent DVR is the lack of open source. Is the lack of which still due to insufficient demand or is it that the licensing issues are insurmountable?

**Comment by ispysoftware** [comment]
@rbukholt well, you could look back over the history of it - all i've been doing is adding stuff to it not removing things from it.
It was only subscriptions originally. I added licensing because it was requested. I'm sure you don't work for free. This is my full time gig.
