### ISSUE TITLE
performance problem if camera is full-screen

### ISSUE THREAD

**Issue by hxl-dy** [ispysoftware/iSpy#83]
reproduce:
1. add a camera source with rtsp realtime-stream(FFmpeg)
2. double click it to make it full-screen
3. wait a few seconds

result:
1. CPU percentage will be doubled when full-screen
2. FPS will be unstable, sometimes up to 90 and down to 12
3. the picture will be bad with mosaic
4. latency will increase obviously
5. exit full-screen will recover

![Untitled](https://user-images.githubusercontent.com/15082228/62767798-057fd500-bac8-11e9-8a32-905413746cc7.png)

**Comment by hxl-dy** [comment]
it seems the reason is that 720p video play full-screen on 1080p screen

**Comment by ispysoftware** [comment]
your pc is just struggling to decode and render the stream in real-time. Try using a lower res stream or see the performance tips link in bottom left of ispy

**Comment by hxl-dy** [comment]
I still don't understand what results that iSpy cannot work as good as vlc or ffplay or other real-time player when rendering on larger resolution than video itself. Is it a design bug, such as rendering is using software way?

**Comment by ispysoftware** [comment]
it's because ffplay and vlc aren't doing motion detection on the frames - they're just decoding and rendering to a hardware surface.

**Comment by hxl-dy** [comment]
Is iSpy able to disable motion detection and just rendering?

**Comment by ispysoftware** [comment]
Sure just.. disable motion detection. It still needs to render on the CPU as it's not using a GPU surface. Our new platform agent does though depending on your hardware.

**Comment by carloselectro** [comment]
I have been struggling a lot to get stable framerate in fullscreen. Disabling motion detection does help but I've found that if my screen resolution is the same as the video resolution the frame rate is stable and fluid. I have an i7,24 gig of RAM and a GTX 750 so it has nothing to do with hardware performance. I did all my tests with one USB webcam (Logitech C920) at 1280X720 30fps.
If my monitor resolution is 1920X1080 the framerates are dropping.
As soon as I set my monitor to 1280X720 everything is fine.I have tried different cameras (Panasonic,Axis,Samsung) on different hardware and I always come with the same results.
I do not have this problem with other software in fullscreen (vlc,blueiris,contacam etc...).
I still want to use ispy because the features are great but the bug in fullscreen is worth investigating.

**Comment by ispysoftware** [comment]
yeah it's because ispy does motion detection and rendering on the CPU so the bottleneck is transferring the video frames to your graphics card. You could try upping the CPU limiter in main ispy settings to 100%.

**Comment by carloselectro** [comment]
I did try the CPU limiter but right now setting my monitor's resolution to match the camera resolution is the only thing that really makes a huge difference. Like I said I did disable all motion detection unless ispy keeps using motion detection when it is turned off.

What about using the vlc plugins with IP camera, would I get better results?
My main priority is the best possible quality and framerate in live view for educational purposes.
Thank you for your help.

**Comment by ispysoftware** [comment]
no the only way to improve it is to have a full GPU pipeline - which is fine if you're just doing playback but if you're processing the video - like looking for motion or encoding to h264  then you either need to write a shader to do that or do it on the CPU like ispy does. If you're just after playback of an ip camera stream on the GPU then just use VLC. You could uncheck "Resize Video" on the first tab when you edit the camera - that might make a difference.
